### ISSUE TITLE
download ggiraph png doesnt work if linebreak in tooltip

### ISSUE THREAD

**Issue by ulrikeniemann** [davidgohel/ggiraph#138]
I am using ggplot and ggiraph in a shiny app. unfortunately when I insert a linebreak in a tooltip, the download-png does not work anymore. I have tried in firefox and chrome. for minimal example see below

```
library(ggplot2)
library(ggiraph)

### download works
my_gg <- ggplot(mpg, aes( x = displ, y = cty) ) + 
  geom_point_interactive(aes(tooltip = paste0(model," ", cty)), size = 2) 
girafe(code = print(my_gg) )

### download doesn't works
my_gg <- ggplot(mpg, aes( x = displ, y = cty) ) + 
  geom_point_interactive(aes(tooltip = paste0(model,"\n", cty)), size = 2) 
girafe(code = print(my_gg) )
```

in the second example nothing happens if ones click on the download-button.

does anyone know the problem?

**Comment by davidgohel** [comment]
I read you SO question, thanks for adding that in GH, I think it's a bug in ggiraph but did not analyse it yet.

david

**Comment by sigmapi** [comment]
This is caused by the html tag <br> inside the tooltip (newlines are converted to <br>).
I've fixed it in the pull request above.

**Comment by ulrikeniemann** [comment]
Finally, I come to test.  I have updated my ggiraph-libary, but the code above is still not working. I have tried to install the CRAN-version and after that the gibhub-version, but downloading a graph with linebreak in tooltip still doesnt work. What should I do to get the bugfix? (additionally: are other HTML tags like <b> allowed?)

**Comment by sigmapi** [comment]
Hi, your code works for me in the latest github version.
Try to reinstall it please from github.
Yes, tooltip can contain full html code

**Comment by ulrikeniemann** [comment]
yes, with complete uninstalling and fresh new install from github it was successfully! I love to use ggiraph in my shiny apps, thank you :)
