### ISSUE TITLE
ggiraph paramaters width and height throw errors

### ISSUE THREAD

**Issue by TomWien** [davidgohel/ggiraph#14]
Just tried running some of your example code, and noticed that whenever width= or height= is used an error is generated: "Error: not compatible with requested type"

For example: 
`ggiraph(code = {print(gg_point_1)}, width = "400px", height = "400px")`

throws the error.  

Other than that, nice piece of code - thanks for sharing.

Tom

**Comment by davidgohel** [comment]
Hi,

Are you using a version < 0.3.0? I submitted yesterday the version 0.3.0 that fix this issue.
https://cran.r-project.org/web/packages/ggiraph/vignettes/ggiraph.html 

David

**Comment by TomWien** [comment]
CRAN served me up 0.2.0.  I just upgraded to 0.3.0 and the error has gone away.  Unfortunately, so have the graphs - I now get a blank screen using the RStudio internal viewer.

Let me go diagnose this some more before you do anything else.  I'm running R 3.2.4 and ggplot2 2.1.0 - these should work ok, right?

Thanks for the quick turnaround.

Tom

**Comment by TomWien** [comment]
Ok, spent some time with it.  Turns out that it seems to be a problem with the RStudio viewer.  With the viewer or Shiny I get nothing at all.  With an external browser (Chrome) it works fine.  Interestingly, I can render the chart to the internal RStudio viewer (which is blank), export it, open it in a real browser, and it works fine.

I just upgraded to RStudio 0.99.896.  I also got the same results on the previous version - 0.99.892.  I am using htmlwidgets 0.6.1.  The problem also occurs with htmlwidgets 0.6.0.

Any ideas?

Tom

**Comment by davidgohel** [comment]
Sorry for the delay.

I think the issue is now solved, could you have a try?

```
# xml2 has changed and the 2 following packages should be updated 
devtools::install_github("hadley/xml2") 
devtools::install_github("davidgohel/rvg")
# new version of ggiraph
devtools::install_github("davidgohel/ggiraph")
```

David

**Comment by TomWien** [comment]
Ok, thanks.  I'll get to it in the next couple of days and get back to you.

Thanks again.

Tom

**Comment by TomWien** [comment]
Same problem.  Graphic works fine in an external browser, but does not render in the RStudio internal viewer.  

Running R 3.3.0 and RStudio 0.99.902, ggiraph 0.3.0.9000 and htmwidgets 0.6

**Comment by davidgohel** [comment]
ok, finally reproduced it, thanks - it only happen on windows...
This is an issue in my code with the resizing method. I will fix that soon and let you know when it will be ok

**Comment by davidgohel** [comment]
Hi,

The new github version should work now. Can you try again please?

David

**Comment by TomWien** [comment]
Ok.   Did you see my latest post that the RStudio viewer is still not 
working?

**Comment by davidgohel** [comment]
Yes,

Did you try the latest version (I have reproduced it and it should be fixed)?
It should be the `0.3.1`

**Comment by TomWien** [comment]
I did.  Let me go back to a clean install and try again.  I'll get back 
to you later today.

**Comment by TomWien** [comment]
On 7/5/2016 11:01 AM, David Gohel wrote:
>
> Yes,
>
> Did you try the latest version (I have reproduced it and it should be 
> fixed)?
> It should be the |0.3.1|
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/davidgohel/ggiraph/issues/14#issuecomment-230504456>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ARIpYMtGU-KthnIj5LJ4ZbAdVPqTmY7Vks5qSnHLgaJpZM4IXuGi>.
>
Did a clean install of everything and now it works.  Currently running 
0.3.1.


Thanks for the help!


Tom

**Comment by davidgohel** [comment]
cool

thanks for the feedback

**Comment by michaelrasmussen1979** [comment]
Hi just trying to overlay individual points from one dataset to a boxplot:
`#Create an initial boxplot object that holds the 'frame' of the boxplots for each category (for which to overlay candidate scores)
boxplot <- ggplot(data = longdata,
           aes(y=category, x=score, tooltip = score)) +
           geom_boxploth(outlier.shape=NA) + 
           ylab("component") +  
           xlab("scores (%)") +
           ggtitle("Clinical Exam") +
           theme_minimal()
boxplot

boxplot_point <- boxplot + geom_point_interactive(data = candidate.162800, aes(y=category, x=round(score,0), tooltip=round(score,0)))

ggiraph(code = print(boxplot_point), width = .5)
`
Which throws up the error:
> Error in alpha(coords$colour, coords$alpha) : 
>   Data must either be a data frame or a matrix

Previously I had trouble/conflict between ggplot2 and the psych packages over 'alpha' but in this case I had not loaded the psych package. 

When I run the stock standard not interactive geom_point everything is fine, i.e.:
boxplot_point <- boxplot + geom_point(data = candidate.162800, aes(y=category, x=round(score,0)))
boxplot_point

AOK

**Comment by wangyueshazi** [comment]
I read through the above conversation, but I still have a question about the width and height setting.
In the package document for function ggiraph(), the parameter "width" sets the widget width ratio, which is between 0 and 1. What if I want the width larger than the height? I tried different approaches, but all failed.
Did I misunderstand the meaning of the parameter "width" or there is another way to set the width and height? Thanks for the consideration.

**Comment by davidgohel** [comment]
read that article: https://davidgohel.github.io/ggiraph/articles/sizing.html

and use parameters: `width_svg`, `height_svg`
