### ISSUE TITLE
ggiraph plots not generating in a shiny modal

### ISSUE THREAD

**Issue by smlehman** [davidgohel/ggiraph#150]
I'm trying to use ggiraph to drill through a bar plot to another ggiraph plot displayed in a shiny modal. 

Everything works fine with the initial plot, and the data id passes the clicked bar value correctly.  The first bar that is clicked displays almost correctly (no interactivity), but when I close the modal and click a second time, no plot appears at all.  I swapped out the ggiraph plot for a ggplot, and the ggplot displays as expected.  

Any thoughts on how one might coax ggiraph to work in a modal?  

I posted this question initially on RStudio with several minimal examples  -- https://community.rstudio.com/t/using-modals-to-display-drill-through-plots-in-shiny-modules/41183?u=stevel

Here is the one that best illustrates this behavior.  
```r
library(shiny)
library(tidyverse)
library(ggiraph)

#function for calling the modal
plotModal <- function(session) {
  modalDialog(
    textOutput("modalText"),
   ggiraphOutput("modalplot")
  )
}

# Main app UI
ui <- fluidPage( ggiraphOutput("mainplot"))

# Main app server
server <- function(input, output, session) {
  
#create main plot
  output$mainplot <-renderggiraph({
    p <- ggplot(mpg, aes( x = class, tooltip = class,
                          data_id = class ) ) +
      geom_bar_interactive()
    ggiraph(code = print(p), selection_type = "single")
  }) 
  
  #Create the drill-through plot
  output$modalplot <- renderggiraph({
    selected_class <-  input$mainplot_selected
    # selected_class <-  compact
    df <- mpg %>% 
      filter(class == selected_class)
    
    p <- ggplot(df, aes(x = cyl, tooltip = class))+
      geom_bar_interactive()
    ggiraph(code = print(p), selection_type = "single")
  })
  
  output$modalText <- renderText({
    selected_class <- input$mainplot_selected
    paste("You have selected", selected_class, ".")
  })
  
  # open modal on plot click using _selected
  observeEvent(input$mainplot_selected,
               ignoreNULL = TRUE,  
               ignoreInit = TRUE,
               showModal(plotModal(session))
  )
}

shinyApp(ui, server)
```

**Comment by davidgohel** [comment]
Dear @smlehman 

I think this issue is solved in the github/dev version. I am not able to reproduce it.

Could you check with the github version?

David

**Comment by smlehman** [comment]
Thanks, @davidgohel 
The github version fixes the issue of no plot appearing on the second click!  However, I'm still not getting interactivity on the plot in the modal.  

Here's an even more simplified version of the reprex.
```r
library(shiny)
library(tidyverse)
devtools::install_github('davidgohel/ggiraph')
library(ggiraph)

# Main app UI
ui <- fluidPage( ggiraphOutput("mainplot"))

# Main app server
server <- function(input, output, session) {
  
  #create main plot
  output$mainplot <-renderggiraph({
    p <- ggplot(mpg, aes( x = class, tooltip = class,
                          data_id = class ) ) +
      geom_bar_interactive()
    ggiraph(code = print(p), selection_type = "single")
  }) 
  
  #Create the drill-through plot
  output$modalplot <- renderggiraph({
    df <- mpg %>% 
      filter(class == input$mainplot_selected)
    p <- ggplot(df, aes(x = cyl, tooltip = class))+
      geom_bar_interactive()
    ggiraph(code = print(p), selection_type = "single")
  })
  
  # open modal on plot click using _selected
  observeEvent(input$mainplot_selected,
               ignoreInit = TRUE,
               showModal(
                 modalDialog(ggiraphOutput("modalplot")
               ))
  )
}

shinyApp(ui, server)
```

**Comment by davidgohel** [comment]
Sorry, I should have seen that.

The code below solve this.  The modal is using a css property named `z-index` greater than the default one set by `girafe`. It has to be set to an higher integer value `girafe_options(z, opts_tooltip(zindex = 9999))`. Note I updated the code with `girafe` instead of `ggiraph`.

```
library(shiny)
library(tidyverse)
library(ggiraph)

#function for calling the modal
plotModal <- function(session) {
  modalDialog(
    textOutput("modalText"),
    ggiraphOutput("modalplot")
  )
}

# Main app UI
ui <- fluidPage( ggiraphOutput("mainplot"))

# Main app server
server <- function(input, output, session) {
  
  #create main plot
  output$mainplot <-renderggiraph({
    p <- ggplot(mpg, aes( x = class, tooltip = class,
                          data_id = class ) ) +
      geom_bar_interactive()
    ggiraph(code = print(p), selection_type = "single")
  }) 
  
  #Create the drill-through plot
  output$modalplot <- renderggiraph({
    selected_class <-  input$mainplot_selected
    # selected_class <-  compact
    df <- mpg %>% 
      filter(class == selected_class)
    
    p <- ggplot(df, aes(x = cyl, tooltip = class))+
      geom_bar_interactive()
    z <- girafe(code = print(p))
    girafe_options(z, opts_tooltip(zindex = 9999))
  })
  
  output$modalText <- renderText({
    selected_class <- input$mainplot_selected
    paste("You have selected", selected_class, ".")
  })
  
  # open modal on plot click using _selected
  observeEvent(input$mainplot_selected,
               ignoreNULL = TRUE,  
               ignoreInit = TRUE,
               showModal(plotModal(session))
  )
}

print(shinyApp(ui, server))
```

**Comment by smlehman** [comment]
Fantastic, David!  Thanks so much.  I'll update the RStudio thread with your solution.

Again, thanks for the excellent package.

**Comment by davidgohel** [comment]
You are welcome
