### ISSUE TITLE
Pb French encoding in ggplot and ggiraph plot

### ISSUE THREAD

**Issue by RozennGZ** [davidgohel/ggiraph#27]
I'm trying to make a plot using ggplot2 and ggiraph in a shiny app with data from a csv file. The csv file has been saved in UTF-8 and read as well with UTF-8 encoding.
In the shiny app, I have no problem of accent when I visualize a text from the input data (with a Textoutput) but in the plot, I don't arrive to manage the accents, which are replaced with other characters. 

![graph_test](https://cloud.githubusercontent.com/assets/20970251/17588774/69a5f226-5fd1-11e6-9fe4-6646891ca3a8.png)

Here, information about my session : 

> sessionInfo()
> R version 3.2.2 (2015-08-14)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

Thanks in advance for your help !!

**Comment by davidgohel** [comment]
This is an issue with Windows encoding. 

This will be fixed but it will take time.

David

**Comment by davidgohel** [comment]
Hi Rozenn,

Please don't close the ticket, this issue will be solved later.

David

**Comment by davidgohel** [comment]
Hi 

I have not started to work on this yet but I hope to find time for this soon.

**Comment by SailingHe** [comment]
It seemed I meet the same problem;
my session:
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

**Comment by grzechowiak** [comment]
Hi, I have the same issue. There is not only a problem with accents but even when I use english words which contains single quotation (I mean: ' ). When I make a plot, R shows an error: str cannot contain single quote "'", and it refers to tooltip in ggiraph.

My session: 
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    
attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
ggiraph_0.3.3     ggplot2_2.2.1    


Thanks in advance!

**Comment by davidgohel** [comment]
@grzechowiak yes, simple quotes should be transformed in HTML codes, I will make a note for that in the doc in the next dev run (soon).

**Comment by grzechowiak** [comment]
@davidgohel you're right, it's working now. Thanks!

**Comment by davidgohel** [comment]
This issue can be close now. It's fixed in the new version of rvg. To test the solution, you need to update `rvg` from github: 

```
devtools::install_github("davidgohel/rvg")
```

The package will probably be submitted to cran this week.

**Comment by mgagliol** [comment]
I seem to still have the "'" issue.

Can you try this code:

```
library("ggplot2")
library("dplyr")
library("gapminder")
library("ggiraph")

data("gapminder")
data("country_colors")

ggint <- ggplot(data = filter(gapminder, year == max(year)),
                mapping = aes(x = gdpPercap, y = lifeExp, size = pop, fill = country)) +
    geom_point_interactive(mapping = aes(tooltip = as.character(country)),
                           color = "gray", shape = 21, alpha = 0.8) +
    scale_x_log10() +
    scale_size_continuous(range = c(1,10)) +
    scale_fill_manual(values = country_colors, guide = FALSE) 

girafe(print(ggint))

```
The error message I get:

> Error in set_attr(ids = as.integer(ids), str = encode_cr(x$tooltip), attribute = "title") : 
>   str cannot contain single quote "'".
> 
> Enter a frame number, or 0 to exit   
> 
>  1: girafe(print(ggint))
>  2: tryCatch({
>     if (!is.null(ggobj)) {
>         stopifnot(inherits(ggobj, "gg
>  3: tryCatchList(expr, classes, parentenv, handlers)
>  4: print(ggint)
>  5: print.ggplot(ggint)
>  6: grid.draw(gtable)
>  7: grid.draw.gTree(gtable)
>  8: recordGraphics(drawGTree(x), list(x = x), getNamespace("grid"))
>  9: drawGTree(x)
> 10: grid.draw(x$children[[i]], recording = FALSE)
> 11: grid.draw.gTree(x$children[[i]], recording = FALSE)
> 12: recordGraphics(drawGTree(x), list(x = x), getNamespace("grid"))
> 13: drawGTree(x)
> 14: grid.draw(x$children[[i]], recording = FALSE)
> 15: grid.draw.grob(x$children[[i]], recording = FALSE)
> 16: recordGraphics(drawGrob(x), list(x = x), getNamespace("grid"))
> 17: drawGrob(x)
> 18: drawDetails(x, recording = FALSE)
> 19: drawDetails.interactive_points_grob(x, recording = FALSE)
> 20: set_attr(ids = as.integer(ids), str = encode_cr(x$tooltip), attribute = "ti

My installation (both ggiraph and rvg just installed via devtools::install_github):

`installed.packages()["ggiraph", "Version"]`

> [1] "0.6.0.001"

`installed.packages()["rvg", "Version"]`

> [1] "0.1.9"

`version`

> platform       x86_64-pc-linux-gnu         
> arch           x86_64                      
> os             linux-gnu                   
> system         x86_64, linux-gnu           
> status                                     
> major          3                           
> minor          4.4                         
> year           2018                        
> month          03                          
> day            15                          
> svn rev        74408                       
> language       R                           
> version.string R version 3.4.4 (2018-03-15)
> nickname       Someone to Lean On          


Any help would be greatly appreciated!

**Comment by davidgohel** [comment]
@mgagliol this is not related to this issue that has been solved. Your issue has been answered here #5
